---
baseurl: "https://pentacode.app/"
title: "Pentacode"
languageCode: "de-de"
defaultContentLanguage: "de"
metaDataFormat: "yaml"
pluralizelisttitles: false
summaryLength: 30
taxonomies:
    magazin/rubrik: magazin/rubriken
params:
    get_started_url: "/#preise"
    contact_url: "mailto:mail@pentacode.app"
outputs:
    section:
        - html
        - json
markup:
    tableOfContents:
        endLevel: 3
        ordered: false
        startLevel: 2
    goldmark:
        renderer:
            unsafe: true
related:
    includeNewer: true
    indices:
        - name: magazin/rubriken
          weight: 100
    threshold: 80
    toLower: true
