---
baseurl: "https://pentacode.app/"
title: "Pentacode"
languageCode: "de-de"
defaultContentLanguage: "de"
metaDataFormat: "yaml"
pluralizelisttitles: false
params:
    get_started_url: "/#angebot"
    contact_url: "mailto:mail@pentacode.app"
outputs:
    section:
        - html
        - json
markup:
    goldmark:
        renderer:
            unsafe: true
